### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by grey-maze** [kuyeseraAi/kai#5]
Explore designs on photos and publications pages.

**Comment by kuyeseraAi** [comment]
I remember we made a detailed list of suggestions. Please record them all. 
Split the task pertaining to publication page from the one that is about photos. 
We talked about a gallery or photos etc. Please copy all the notes you made during our meeting in a way that is precise.

**Comment by grey-maze** [comment]
The tasks were separated and done individually.
